### ISSUE TITLE
[BUG] Send blocking

### ISSUE THREAD

**Issue by ForteScarlet** [ForteScarlet/simpler-robot#118]
```
java.lang.InterruptedException: null
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:83) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at love.forte.simbot.component.mirai.sender.MiraiSender.sendGroupMsg0(MiraiSender.kt:104) ~[component-mirai-2.0.9.jar!/:na]
        at love.forte.simbot.component.mirai.sender.MiraiSender.sendGroupMsg(MiraiSender.kt:126) ~[component-mirai-2.0.9.jar!/:na]
        at love.forte.bot.bot.listener.AliveListener.alive(logoutListener.kt:55) ~[classes!/:1.0-SNAPSHOT]
        at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_191]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_191]
```

**Comment by ForteScarlet** [comment]
maybe runBlocking deadlock.

**Comment by ForteScarlet** [comment]
#92
