### ISSUE TITLE
[SUG]希望提供mirai事件MessagePostSendEvent以及其子类的事件

### ISSUE THREAD

**Issue by kukume** [ForteScarlet/simpler-robot#148]
## 建议描述
希望提供mirai事件MessagePostSendEvent以及其子类的事件
另外希望可以手动注册mirai自带事件或者其他事件

**Comment by ForteScarlet** [comment]
#150

**Comment by kukume** [comment]
kotlin的  是把方法写在哪？随便写在哪都可以吗？

**Comment by ForteScarlet** [comment]
参考https://www.yuque.com/simpler-robot/simpler-robot-doc/mrzn2w，一般放在main的开始就行，我觉得

**Comment by kukume** [comment]
是这样用的吗？
注册事件
```kotlin
class MiraiMessagePostSendEvent(event: GroupMessagePostSendEvent): AbstractMiraiMsgGet<GroupMessagePostSendEvent>(event), MsgGet {
    override val text = "haha"
    override val accountInfo = event.bot.asAccountInfo()
    override val id = if (event.message.ids.isNotEmpty()){ event.message.ids[0].toString() } else ""
}

@Component
class RegisterMessagePostSendEvent: BeanPostProcessor{
    @PostConstruct
    fun register(){
        registerEventSolver(GroupMessagePostSendEvent::class, MiraiMessagePostSendEvent::class) {
            MiraiMessagePostSendEvent(it)
        }
    }
}
```


然后监听：
```java
@Listen(MiraiMessagePostSendEvent.class)
	public void listen(){
		System.out.println("haha");
	}
```


最后面报错了java.util.NoSuchElementException: net.mamoe.mirai.message.data.MessageSource$Key@40a2790

**Comment by ForteScarlet** [comment]
提供完整错误日志

**Comment by kukume** [comment]
```
java.util.NoSuchElementException: net.mamoe.mirai.message.data.MessageSource$Key@40a2790
	at me.kuku.simbot.event.MiraiMessagePostSendEvent.<init>(RegisterEvent.kt:33) ~[classes/:na]
	at me.kuku.simbot.event.RegisterMessagePostSendEvent$register$1.invoke(RegisterEvent.kt:25) ~[classes/:na]
	at me.kuku.simbot.event.RegisterMessagePostSendEvent$register$1.invoke(RegisterEvent.kt:24) ~[classes/:na]
	at love.forte.simbot.component.mirai.utils.MiraiBotEventRegistrar$registerSimbotEvents$1$40$1$1.invokeSuspend(MiraiBotEventRegistrar.kt:381) ~[component-mirai-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiBotEventRegistrar$registerSimbotEvents$1$40$1$1.invoke(MiraiBotEventRegistrar.kt) ~[component-mirai-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiBotEventRegistrar$registerSimbotEvents$1$40$1$1.invoke(MiraiBotEventRegistrar.kt) ~[component-mirai-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiBotEventRegistrar$registerListenerAlways$2.invokeSuspend(MiraiBotEventRegistrar.kt:414) ~[component-mirai-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiBotEventRegistrar$registerListenerAlways$2.invoke(MiraiBotEventRegistrar.kt) ~[component-mirai-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.component.mirai.utils.MiraiBotEventRegistrar$registerListenerAlways$2.invoke(MiraiBotEventRegistrar.kt) ~[component-mirai-2.2.0-BETA.4.jar:na]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:431) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invokeSuspend(EventChannel.kt:145) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invokeSuspend(EventChannel.kt:145) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:49) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:49) ~[mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:226) [mirai-core-api-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:139) [mirai-core-jvm-2.6.7.jar:na]
	at net.mamoe.mirai.internal.contact.GroupImpl$sendMessage$1.invokeSuspend(GroupImpl.kt) [mirai-core-jvm-2.6.7.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at love.forte.simbot.component.mirai.sender.MiraiSender.sendGroupMsg0(MiraiSender.kt:117) [component-mirai-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.component.mirai.sender.MiraiSender.sendGroupMsg(MiraiSender.kt:148) [component-mirai-2.2.0-BETA.4.jar:na]
	at me.kuku.simbot.config.QuickReplyProcessor.sendMessage(QuickReplyProcessor.java:85) [classes/:na]
	at me.kuku.simbot.config.QuickReplyProcessor.processor(QuickReplyProcessor.java:54) [classes/:na]
	at love.forte.simbot.core.processor.CoreListenResultProcessorManager.processor(CoreListenResultProcessorManager.kt:68) [core-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.core.listener.CoreListenerManager.onMsg0$doListen(CoreListenerManager.kt:359) [core-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.core.listener.CoreListenerManager.onMsg0(CoreListenerManager.kt:396) [core-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.core.listener.CoreListenerManager.onMsg1(CoreListenerManager.kt:274) [core-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.core.listener.CoreListenerManager.access$onMsg1(CoreListenerManager.kt:93) [core-2.2.0-BETA.4.jar:na]
	at love.forte.simbot.core.listener.CoreListenerManager$onMsg$2.invokeSuspend(CoreListenerManager.kt:236) [core-2.2.0-BETA.4.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_291]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_291]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_291]
```

**Comment by ForteScarlet** [comment]
`RegisterEvent.kt:33` 是哪一行代码

**Comment by kukume** [comment]
![image](https://user-images.githubusercontent.com/45278810/127773898-d2b9cf00-708f-470e-bb10-f29503b6f1e4.png)
这是我的类文件截图。没有33行。。。

**Comment by ForteScarlet** [comment]
参考Mirai源码 `MessageChain.getOrFail (MessageChain:371-374)` ， 你的代码第16行 `event.message.ids` 会报错

**Comment by fiftn** [comment]
6666，群主我爱你
