### ISSUE TITLE
[QU.]用的2.3.0-BETA.1版，simbot-mirai-springboot-starter-demo，使用持续会话作用域超时报错。

### ISSUE THREAD

**Issue by YongKp123** [ForteScarlet/simpler-robot#174]
version: `` 

## 疑问描述
我用的2.3.0-BETA.1版，simbot-mirai-springboot-starter-demo，直接复制的TestListener这个Java示例，运行之后没有进入第一个会话的监听，输入手机号之后等一分钟直接超时失败了。

[simbot-mirai-spring-boot-demo-master.zip](https://github.com/ForteScarlet/simpler-robot/files/7440725/simbot-mirai-spring-boot-demo-master.zip)

启动时有异常如下：
2021-10-29 17:09:13.048 DEBUG 2304 --- [           main] .f.s.c.c.CoreMethodPostListenerRegistrar : Cannot get type class org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$ClassProxyingConfiguration$$Lambda$255/460741164 functions, skip.

kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: class org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$ClassProxyingConfiguration$$Lambda$255/460741164
	at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:329) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl.getMemberScope$kotlin_reflection(KClassImpl.kt:191) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:162) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:47) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(KClassImpl.kt) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:171) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:47) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllNonStaticMembers(KClassImpl.kt) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allMembers$2.invoke(KClassImpl.kt:177) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allMembers$2.invoke(KClassImpl.kt:47) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllMembers(KClassImpl.kt) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.jvm.internal.KClassImpl.getMembers(KClassImpl.kt:195) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.reflect.full.KClasses.getFunctions(KClasses.kt:90) ~[kotlin-reflect-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar$registerListenerFunctions$2.invoke(CoreMethodPostListenerRegistrar.kt:103) [core-2.3.0-BETA.1.jar:na]
	at love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar$registerListenerFunctions$2.invoke(CoreMethodPostListenerRegistrar.kt:94) [core-2.3.0-BETA.1.jar:na]
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315) [kotlin-stdlib-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303) [kotlin-stdlib-1.5.20.jar:1.5.20-release-287 (1.5.20)]
	at love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar.registerListenerFunctions(CoreMethodPostListenerRegistrar.kt:166) [core-2.3.0-BETA.1.jar:na]
	at love.forte.simbot.core.configuration.CoreListenerRegistrar.registerListeners(CoreListenerRegistrar.kt:55) [core-2.3.0-BETA.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at love.forte.common.ioc.MethodDependPass.invoke(DependPass.kt:76) [ioc-1.0.7.jar:na]
	at love.forte.common.ioc.DependCenter.init(DependCenter.kt:108) [ioc-1.0.7.jar:na]
	at love.forte.simbot.core.SimbotApp.initDependCenter(SimbotApp.kt:434) [core-2.3.0-BETA.1.jar:na]
	at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:279) [core-2.3.0-BETA.1.jar:na]
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:509) [core-2.3.0-BETA.1.jar:na]
	at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt) [core-2.3.0-BETA.1.jar:na]
	at love.forte.simbot.spring.autoconfigure.SimbotAppConfiguration.simbotApp(SimbotAppConfiguration.java:84) [core-spring-boot-starter-2.3.0-BETA.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) ~[spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) ~[spring-boot-2.5.0.jar:2.5.0]
	at simbot.example.SimbotExampleApplication.main(SimbotExampleApplication.java:18) ~[classes/:na]

使用会话作用域时报错如下：
onCancel 关闭啦: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 60000 ms
onError: 出错啦: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 60000 ms

**Comment by YongKp123** [comment]
加上@OnGroup或者@OnPrivate，群聊和私聊都可以了，感谢大佬
