### ISSUE TITLE
[BUG] 升级到2.3.0之后，@OnGroup @OnPrivate同时存在会导致发消息会提示错误

### ISSUE THREAD

**Issue by lifespy** [ForteScarlet/simpler-robot#175]
version: `2.3.0-BETA.2`

module: ``

## 疑问描述

升级到2.3.0之后，@OnGroup @OnPrivate同时存在会导致发消息会提示错误
![1](https://user-images.githubusercontent.com/10860818/139635430-c285018f-61a4-4780-aaff-825e3046df57.png)
![2](https://user-images.githubusercontent.com/10860818/139635437-3c2fdd0c-f380-42a8-bc63-ba8a0dc7c4ce.png)

**Comment by lifespy** [comment]
完整错误日志：
`2021-11-01 15:17:59.710 ERROR 44172 --- [-dispatcher-M-1] pi.sender.MsgSender): kotlin.Unit.dogLog : Listener execution exception: love.forte.common.ioc.exception.NoSuchDependException: interface love.forte.simbot.api.message.events.GroupMsg

love.forte.common.ioc.exception.NoSuchDependException: interface love.forte.simbot.api.message.events.GroupMsg
	at love.forte.common.ioc.DependCenter.get(DependCenter.kt:944)
	at love.forte.simbot.core.listener.ListenerFunctionInvokeDataImpl.get(ListenerFunctionDataImpl.kt:53)
	at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$toParameterGetter$10.invoke(FunctionFromClassListenerFunction.kt:454)
	at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$toParameterGetter$10.invoke(FunctionFromClassListenerFunction.kt:448)
	at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$8.invoke(FunctionFromClassListenerFunction.kt:249)
	at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$8.invoke(FunctionFromClassListenerFunction.kt:249)
	at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$invoker$1.invokeSuspend(FunctionFromClassListenerFunction.kt:609)
	at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$invoker$1.invoke(FunctionFromClassListenerFunction.kt)
	at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$invoker$1.invoke(FunctionFromClassListenerFunction.kt)
	at love.forte.simbot.core.listener.FunctionFromClassListenerFunction.invoke(FunctionFromClassListenerFunction.kt:638)
	at love.forte.simbot.core.listener.ListenerInvokerImpl.invoke(ListenerInvokerImpl.kt:36)
	at love.forte.simbot.core.listener.CoreListenerManager$doListenerFunctionInvoker$2.invokeSuspend(CoreListenerManager.kt:475)
	at love.forte.simbot.core.listener.CoreListenerManager$doListenerFunctionInvoker$2.invoke(CoreListenerManager.kt)
	at love.forte.simbot.core.listener.CoreListenerManager$doListenerFunctionInvoker$2.invoke(CoreListenerManager.kt)
	at love.forte.simbot.core.listener.CoreListenerManager.onMsg0$doListen(CoreListenerManager.kt:521)
	at love.forte.simbot.core.listener.CoreListenerManager.onMsg0(CoreListenerManager.kt:585)
	at love.forte.simbot.core.listener.CoreListenerManager.onMsg1(CoreListenerManager.kt:443)
	at love.forte.simbot.core.listener.CoreListenerManager.access$onMsg1(CoreListenerManager.kt:115)
	at love.forte.simbot.core.listener.CoreListenerManager$onMsg$2.invokeSuspend(CoreListenerManager.kt:412)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: love.forte.common.ioc.exception.NoSuchDependException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'love.forte.simbot.api.message.events.GroupMsg' available
	at love.forte.simbot.spring.autoconfigure.SpringDependBeanFactory.get(SpringDependBeanFactory.java:53)
	at love.forte.common.ioc.DependCenter.get(DependCenter.kt:936)
	... 23 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'love.forte.simbot.api.message.events.GroupMsg' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at love.forte.simbot.spring.autoconfigure.SpringDependBeanFactory.get(SpringDependBeanFactory.java:51)
	... 24 common frames omitted`
