### ISSUE TITLE
[BUG] 消息撤回时触发时间报异常

### ISSUE THREAD

**Issue by ilxyil** [ForteScarlet/simpler-robot#185]
version: `2.2.3` 

## 问题描述

消息撤回时，报了NoSuchBeanDefinitionException: No qualifying bean of type 'love.forte.simbot.api.message.events.PrivateMsg' available 异常
## 相关日志

Listener execution exception: love.forte.common.ioc.exception.NoSuchDependException: interface love.forte.simbot.api.message.events.PrivateMsg

love.forte.common.ioc.exception.NoSuchDependException: interface love.forte.simbot.api.message.events.PrivateMsg
 at love.forte.common.ioc.DependCenter.get(DependCenter.kt:944) ~[ioc-1.0.6.jar!/:na]
 at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$toParameterGetter$11.invoke(FunctionFromClassListenerFunction.kt:459) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$toParameterGetter$11.invoke(FunctionFromClassListenerFunction.kt:453) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$7.invoke(FunctionFromClassListenerFunction.kt:243) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$7.invoke(FunctionFromClassListenerFunction.kt:243) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$invoker$1.invokeSuspend(FunctionFromClassListenerFunction.kt:603) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$invoker$1.invoke(FunctionFromClassListenerFunction.kt) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.FunctionFromClassListenerFunction$invoker$1.invoke(FunctionFromClassListenerFunction.kt) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.FunctionFromClassListenerFunction.invoke(FunctionFromClassListenerFunction.kt:632) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.ListenerInvokerImpl.invoke(ListenerInvokerImpl.kt:34) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.CoreListenerManager$doListenerFunctionInvoker$2.invokeSuspend(CoreListenerManager.kt:306) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.CoreListenerManager$doListenerFunctionInvoker$2.invoke(CoreListenerManager.kt) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.CoreListenerManager$doListenerFunctionInvoker$2.invoke(CoreListenerManager.kt) ~[core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.CoreListenerManager.onMsg0$doListen(CoreListenerManager.kt:351) [core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.CoreListenerManager.onMsg0(CoreListenerManager.kt:396) [core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.CoreListenerManager.onMsg1(CoreListenerManager.kt:274) [core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.CoreListenerManager.access$onMsg1(CoreListenerManager.kt:93) [core-2.2.3.jar!/:na]
 at love.forte.simbot.core.listener.CoreListenerManager$onMsg$2.invokeSuspend(CoreListenerManager.kt:236) [core-2.2.3.jar!/:na]
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.5.20.jar!/:1.5.20-release-287 (1.5.20)]
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.5.0.jar!/:na]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_311]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_311]
 at java.lang.Thread.run(Thread.java:748) [na:1.8.0_311]
Caused by: love.forte.common.ioc.exception.NoSuchDependException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'love.forte.simbot.api.message.events.PrivateMsg' available
 at love.forte.simbot.spring.autoconfigure.SpringDependBeanFactory.get(SpringDependBeanFactory.java:53) ~[core-spring-boot-starter-2.2.3.jar!/:na]
 at love.forte.common.ioc.DependCenter.get(DependCenter.kt:936) ~[ioc-1.0.6.jar!/:na]
 ... 22 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'love.forte.simbot.api.message.events.PrivateMsg' available
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:351) ~[spring-beans-5.3.7.jar!/:5.3.7]
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342) ~[spring-beans-5.3.7.jar!/:5.3.7]
 at love.forte.simbot.spring.autoconfigure.SpringDependBeanFactory.get(SpringDependBeanFactory.java:51) ~[core-spring-boot-starter-2.2.3.jar!/:na]

**Comment by ForteScarlet** [comment]
私聊消息撤回事件的参数实例是 `PrivateMsgRecall`, 不是 `PrivateMsg`。群聊同理。

<https://www.yuque.com/simpler-robot/simpler-robot-doc/ct1u6l#m0od6>
