### ISSUE TITLE
[QU.] 启动时出现 NoSuchDependException: love.forte.simbot.api.sender.SenderFactory

### ISSUE THREAD

**Issue by YunHerry** [ForteScarlet/simpler-robot#186]
version:  2.3.3

module: ``
## pom
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>top.yun</groupId>
    <artifactId>YuBot</artifactId>
    <version>1.0-Beta</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <simbot.version>2.3.3</simbot.version>
    </properties>
    
    
    
    
    
    
    <dependencies>
        
        <dependency>
            <groupId>love.forte.simple-robot</groupId>
            <artifactId>component-mirai</artifactId>
            <version>${simbot.version}</version>
            <type>pom</type>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                    <compilerArgs>
                        <arg>-parameters</arg>
                    </compilerArgs>
                </configuration>
            </plugin>

            
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.3.4.RELEASE</version>
                <configuration>
                    <mainClass>top.yun.YuBot</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
## 疑问描述
初始化失败,maven项目,按照demo的启动类配置的

```
` ___  ____  __  __  ____  _____  ____
/ __)(_  _)(  \/  )(  _ \(  _  )(_  _)
\__ \ _)(_  )    (  ) _ < )(_)(   )(
(___/(____)(_/\/\_)(____/(_____) (__)
                         @ForteScarlet
                                v2.3.3

Tips: 沉默不代表失败，相反，它往往宣誓胜利。

[2021-11-26T20:31:22.894]-[INFO ] |                    top.yun.YuBot : Active resources: [simbot.yaml]
Exception in thread "main" love.forte.common.ioc.exception.NoSuchDependException: love.forte.simbot.api.sender.SenderFactory
class:     public final class love.forte.simbot.core.configuration.CoreMsgSenderFactoriesConfiguration
method:    public final MsgSenderFactories coreMsgSenderFactories(SenderFactory, SetterFactory, GetterFactory)
parameter: 0:senderFactory SenderFactory
	at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$parameterSupplierList$1$1.invoke$lambda-0(DependCenter.kt:531)
	at love.forte.common.ioc.DependCenter.getOrThrow(DependCenter.kt:1033)
	at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$parameterSupplierList$1$1.invoke(DependCenter.kt:530)
	at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$parameterSupplierList$1$1.invoke(DependCenter.kt:529)
	at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$1.invoke(DependCenter.kt:601)
	at love.forte.common.ioc.DependCenter$childMethodToEmptyInstanceSupplier$1.invoke(DependCenter.kt:589)
	at love.forte.common.ioc.DependCenter$injectChildren$3.invoke$lambda-1(DependCenter.kt:362)
	at love.forte.common.ioc.DependCenter$injectChildren$3.invoke$lambda-4(DependCenter.kt:374)
	at love.forte.common.ioc.DependCenters$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(DependCenter.kt)
	at love.forte.common.ioc.DependCenters$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(DependCenter.kt:298)
	at love.forte.common.ioc.BeanDependBuilder$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(BeanDepend.kt)
	at love.forte.common.ioc.BeanDependBuilder$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(BeanDepend.kt:215)
	at love.forte.common.ioc.DependCenter.getOrThrow(DependCenter.kt:1032)
	at love.forte.common.ioc.DependCenter$constrInstance$parameterGetterList$1$4.invoke(DependCenter.kt:442)
	at love.forte.common.ioc.DependCenter$constrInstance$parameterGetterList$1$4.invoke(DependCenter.kt:442)
	at love.forte.common.ioc.DependCenter$constrInstance$1.invoke(DependCenter.kt:447)
	at love.forte.common.ioc.DependCenter$constrInstance$1.invoke(DependCenter.kt:447)
	at love.forte.common.ioc.DependCenter.inject0$lambda-10(DependCenter.kt:264)
	at love.forte.common.ioc.DependCenter.inject0$lambda-12(DependCenter.kt:279)
	at love.forte.common.ioc.DependCenters$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(DependCenter.kt)
	at love.forte.common.ioc.DependCenters$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(DependCenter.kt:298)
	at love.forte.common.ioc.BeanDependBuilder$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(BeanDepend.kt)
	at love.forte.common.ioc.BeanDependBuilder$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(BeanDepend.kt:215)
	at love.forte.common.ioc.DependCenter.getOrThrow(DependCenter.kt:1032)
	at love.forte.common.ioc.DependCenter$instanceInjectFunc$funcs$1$instance$2.invoke(DependCenter.kt:663)
	at love.forte.common.ioc.DependCenter$instanceInjectFunc$funcs$1$instance$2.invoke(DependCenter.kt:662)
	at love.forte.common.ioc.DependCenter$instanceInjectFunc$funcs$1$1.invoke(DependCenter.kt:735)
	at love.forte.common.ioc.DependCenter$instanceInjectFunc$funcs$1$1.invoke(DependCenter.kt:733)
	at love.forte.common.ioc.DependCenter$instanceInjectFunc$2.invoke(DependCenter.kt:743)
	at love.forte.common.ioc.DependCenter$instanceInjectFunc$2.invoke(DependCenter.kt:742)
	at love.forte.common.ioc.DependCenter.inject0$lambda-10(DependCenter.kt:265)
	at love.forte.common.ioc.DependCenter.inject0$lambda-12(DependCenter.kt:279)
	at love.forte.common.ioc.DependCenters$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(DependCenter.kt)
	at love.forte.common.ioc.DependCenters$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(DependCenter.kt:298)
	at love.forte.common.ioc.BeanDependBuilder$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(BeanDepend.kt)
	at love.forte.common.ioc.BeanDependBuilder$sam$love_forte_common_ioc_InstanceSupplier$0.invoke(BeanDepend.kt:215)
	at love.forte.common.ioc.DependCenter.init(DependCenter.kt:102)
	at love.forte.simbot.core.SimbotApp.initDependCenter(SimbotApp.kt:434)
	at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:279)
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:509)
	at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:472)
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt)
	at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
	at top.yun.YuBot.main(YuBot.java:13)

Process finished with exit code 1`


```

**Comment by ForteScarlet** [comment]
移除你 `pom.xml` 中依赖 `love.forte.simple-robot:component-mirai` 下的 ` <type>pom</type>` 后再做尝试

**Comment by YunHerry** [comment]
已解决()
