### ISSUE TITLE
登录成功了，还是说验证失败，这是为什么呢？[QU.]

### ISSUE THREAD

**Issue by fiftn** [ForteScarlet/simpler-robot#188]
## 疑问描述
```
[2021-12-06T17:19:19.602]-[INFO ] |                    love.f.s.c.m.b.3288244490 : Bot login successful.
[2021-12-06T17:19:19.604]-[INFO ] |                    love.f.s.c.m.n.3288244490 : Scheduled key refresh in 23h 55min 0.0s.
[2021-12-06T17:19:19.604]-[INFO ] |                    love.f.s.c.m.n.3288244490 : Scheduled refresh login session in 19d 23h 55min 0.0s.
[2021-12-06T17:19:19.638]-[ERROR] |              love.f.s.c.m.c.MiraiBotVerifier : Verifier bot(账号) failed.
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at love.forte.common.ioc.MethodDependPass.invoke(DependPass.kt:76)
	at love.forte.common.ioc.DependCenter.init(DependCenter.kt:108)
	at love.forte.simbot.core.SimbotApp.initDependCenter(SimbotApp.kt:434)
	at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:279)
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:509)
	at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:472)
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt)
	at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
	at love.simbot.example.SimbotExampleApplication.main(SimbotExampleApplication.java:41)
Caused by: love.forte.simbot.bot.BotVerifyException: Cannot verifier bot code: 账号
	at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:115)
	at love.forte.simbot.component.mirai.configuration.MiraiBotManager.registerBot(MiraiBotManager.kt:103)
	at love.forte.simbot.core.configuration.CoreBotRegistrar.registerBots(CoreBotRegistrar.kt:65)
	... 13 more
Caused by: java.lang.NumberFormatException: For input string: "账号"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at love.forte.simbot.component.mirai.configuration.MiraiBotVerifier.verity(MiraiBotVerifier.kt:75)
	... 15 more

```
为什么我登录成功突然跳出来验证失败嘞，会不会和下面这段日志有关，这段日志出现在上面那段的前面

```
2021-12-06 17:18:45 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2021-12-06 17:18:45 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
[2021-12-06T17:19:12.518]-[WARN ] |                    love.f.s.c.m.n.3288244490 : null
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /14.215.138.110:8080
	Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@963176
	Caused by: [CIRCULAR REFERENCE: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /14.215.138.110:8080]
	Suppressed: [CIRCULAR REFERENCE: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@963176]
Caused by: java.net.ConnectException: Connection timed out: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[2021-12-06T17:19:13.543]-[INFO ] |                    love.f.s.c.m.n.3288244490 : ECDH key is invalid, start to fetch ecdh public key from server.
[2021-12-06T17:19:14.730]-[INFO ] |                    love.f.s.c.m.n.3288244490 : Successfully fetched ecdh public key from server.
```

我使用的是[https://github.com/simple-robot/simbot-mirai-demo](url)这个例子

**Comment by ForteScarlet** [comment]
检查你的 `resouces/simbot-bots` 目录，删除多余不需要的文件。

**Comment by fiftn** [comment]
解决了，我爱你群主，我要给你生猴子！

**Comment by fiftn** [comment]
哦不，应该是老公~
