### ISSUE TITLE
[QU.]项目打包后执行jar报错

### ISSUE THREAD

**Issue by GinWineLi** [ForteScarlet/simpler-robot#207]
version: `2.3.5` 

module: ``

## 疑问描述

在使用mvn package完成项目jar包构建后，执行文件出现以下错误

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: love.forte.common.ioc.exception.IllegalTypeException: interface love.forte.common.ioc.annotation.SpareBeans cannot be interface or abstract.
        at love.forte.common.ioc.DependCenter.inject0(DependCenter.kt:217)
        at love.forte.common.ioc.DependCenter.inject(DependCenter.kt:199)
        at love.forte.common.ioc.DependCenter.inject$default(DependCenter.kt:197)
        at love.forte.simbot.core.SimbotApp.scanPackagesAndInject(SimbotApp.kt:418)
        at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:276)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:509)
        at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:472)
        at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt)
        at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
        at SimbotExampleApplication.main(SimbotExampleApplication.java:52)
```
pom.xml内容如下
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>simbot.example</groupId>
    <artifactId>simbot-mirai-demo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <simbot.version>2.3.4</simbot.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.dom4j</groupId>
            <artifactId>dom4j</artifactId>
            <version>2.1.3</version>
        </dependency>
        <!-- 使用 mirai 组件。 -->
        <dependency>
            <groupId>love.forte.simple-robot</groupId>
            <artifactId>component-mirai</artifactId>
            <version>${simbot.version}</version><!--vv-->
        </dependency>
        <dependency>
            <groupId>love.forte.common</groupId>
            <artifactId>ioc</artifactId>
            <version>1.0.7</version>
        </dependency>
        <!-- 使用fastjson -->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.75</version>
        </dependency>
        <!-- 定时任务模块 -->
<!--        <dependency>-->
<!--            <groupId>love.forte.simple-robot.time-task</groupId>-->
<!--            <artifactId>time-task-quartz</artifactId>-->
<!--            <version>${simbot.version}</version>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.dom4j</groupId>
                <artifactId>dom4j</artifactId>
                <version>2.1.3</version>
            </plugin>
            <!-- Springboot打包插件。使用 mvn package 进行打包。 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.5.3</version>
                <configuration>
                    <!-- main方法所在类。 -->
                    <mainClass>SimbotExampleApplication</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by GinWineLi** [comment]
![QQ截图20220203185632](https://user-images.githubusercontent.com/59389583/152329887-5e44d880-e532-445e-a851-b2448d358faf.png)
项目结构如以上所示

**Comment by ForteScarlet** [comment]
给你的整个项目代码增加一到多层包结构，例如 `com.example.xxx` 之后再做尝试。

**Comment by GinWineLi** [comment]
> 给你的整个项目代码增加一到多层包结构，例如 `com.example.xxx` 之后再做尝试。

当我将项目结构调整为下图后
![QQ截图20220203185632](https://user-images.githubusercontent.com/59389583/152337787-601de429-8954-4228-b527-a5866c7947bc.png)
重构jar包，再次运行jar仍然出现了以下报错
```
Exception in thread "main" java.lang.ClassNotFoundException: com.simbot.qing.SimbotExampleApplication.java
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```
此时pom.xml对应的限定类名如下
![QQ截图20220203200216](https://user-images.githubusercontent.com/59389583/152339257-ba9faa4d-799e-4147-85b4-9ca8b8133cbc.png)

**Comment by ForteScarlet** [comment]
`pom.xml` 中 `mainClass` 最后那个 `.java` 是无意义的，去掉

**Comment by GinWineLi** [comment]
> `pom.xml` 中 `mainClass` 最后那个 `.java` 是无意义的，去掉

问题已解决，麻烦您了。感谢解答！
