### ISSUE TITLE
Q: v2.3.4 启动时提示Exception in decoding packet.

### ISSUE THREAD

**Issue by Chowhound-ch** [ForteScarlet/simpler-robot#258]
### 疑问描述

**昨天写的还好好的，今天上来刚写十来行就登录报错，把我写的都注释掉了还是报错**

[2022-04-25T17:53:34.123878900]-[INFO ] | love.simbot.example.SimbotExampleApplication : Active resources: [simbot.properties, simbot.yml]
[2022-04-25T17:53:34.799074600]-[INFO ] |          org.quartz.impl.StdSchedulerFactory : Using default implementation for ThreadExecutor
[2022-04-25T17:53:34.802064700]-[INFO ] |            org.quartz.simpl.SimpleThreadPool : Job execution threads will use class loader of thread: main
[2022-04-25T17:53:34.809046200]-[INFO ] |        org.quartz.core.SchedulerSignalerImpl : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[2022-04-25T17:53:34.809046200]-[INFO ] |              org.quartz.core.QuartzScheduler : Quartz Scheduler v.2.3.2 created.
[2022-04-25T17:53:34.809046200]-[INFO ] |                 org.quartz.simpl.RAMJobStore : RAMJobStore initialized.
[2022-04-25T17:53:34.810043400]-[INFO ] |              org.quartz.core.QuartzScheduler : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'SimbotQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[2022-04-25T17:53:34.810043400]-[INFO ] |          org.quartz.impl.StdSchedulerFactory : Quartz scheduler 'SimbotQuartzScheduler' initialized from an externally provided properties instance.
[2022-04-25T17:53:34.810043400]-[INFO ] |          org.quartz.impl.StdSchedulerFactory : Quartz scheduler version: 2.3.2
[2022-04-25T17:53:34.859910800]-[INFO ] |  love.f.s.c.m.c.MiraiEventCacheConfiguration : Disable default mirai message cache.
2022-04-25 17:53:34 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-04-25 17:53:34 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
[2022-04-25T17:53:35.838433]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Server list: 111.30.187.200:80, msfwifi.3g.qq.com:8080, 120.232.67.156:80, 111.30.187.227:14000, 39.156.125.70:443, 120.232.18.213:80, 39.156.126.164:14000, 39.156.125.66:80, 120.232.31.192:80, 120.232.69.173:8080.
[2022-04-25T17:53:36.337375200]-[INFO ] |                    love.f.s.c.m.b.2385607214 : Loaded account secrets from local cache.
[2022-04-25T17:53:36.338373100]-[INFO ] |                    love.f.s.c.m.n.2385607214 : ECDH key is valid.
[2022-04-25T17:53:36.592840400]-[INFO ] |                    love.f.s.c.m.b.2385607214 : Saved account secrets to local cache for fast login.
[2022-04-25T17:53:36.688067900]-[ERROR] |                    love.f.s.c.m.n.2385607214 : Exception in decoding packet.
java.lang.IllegalStateException: type mismatch. Expected SIMPLE_LIST or LIST, got TarsHead(tag=1, type=8(Map)) instead
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.beginStructure(TarsDecoder.kt:260)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder$MapReaderImpl.beginStructure(TarsDecoder.kt:149)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)
	at kotlinx.serialization.internal.PrimitiveArraySerializer.deserialize(CollectionSerializers.kt:179)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
	at kotlinx.serialization.internal.MapLikeSerializer.readAll(CollectionSerializers.kt:96)
	at kotlinx.serialization.internal.MapLikeSerializer.readAll(CollectionSerializers.kt:84)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:31)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3$$serializer.deserialize(RequestPacket.kt:33)
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3$$serializer.deserialize(RequestPacket.kt:33)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Tars.kt:42)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:42)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:121)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:85)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(ConfigPushSvc.kt:78)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
[2022-04-25T17:53:36.791653100]-[INFO ] |                    love.f.s.c.m.b.2385607214 : Login successful.
[2022-04-25T17:53:36.791653100]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Server time updated, serverTime: 1650880419, diff: 3ms=0.003s
[2022-04-25T17:53:36.797116900]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Syncing friend message history...
[2022-04-25T17:53:36.801106300]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Start loading friend list...
[2022-04-25T17:53:36.802102500]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Start loading stranger list...
[2022-04-25T17:53:36.885762100]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Successfully loaded stranger list: 0 in total
[2022-04-25T17:53:36.972745100]-[INFO ] |                    love.f.s.c.m.n.2385607214 : No OtherClient online.
[2022-04-25T17:53:36.973742500]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Start loading group list...
[2022-04-25T17:53:36.978729300]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Syncing friend message history: Success.
[2022-04-25T17:53:37.003052900]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Successfully loaded friend list: 3 in total
[2022-04-25T17:53:37.411991200]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Successfully loaded group list: 2 in total.
[2022-04-25T17:53:37.417973300]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Scheduled key refresh in 23h 55min 0.0s.
[2022-04-25T17:53:37.417973300]-[INFO ] |                    love.f.s.c.m.n.2385607214 : Scheduled refresh login session in 19d 23h 55min 0.0s.
[2022-04-25T17:53:37.417973300]-[INFO ] |                    love.f.s.c.m.b.2385607214 : Bot login successful.
[2022-04-25T17:53:37.430952100]-[INFO ] | love.f.s.c.c.CoreMethodPostListenerRegistrar : Ready to register method listeners.
[2022-04-25T17:53:37.430952100]-[INFO ] | love.f.s.c.c.CoreMethodPostListenerRegistrar : If you want to view the details, please enable log debug.
[2022-04-25T17:53:37.741687700]-[INFO ] | love.f.s.c.c.CoreMethodPostListenerRegistrar : Method listeners Registration is complete.
[2022-04-25T17:53:38.194272800]-[INFO ] |           love.f.s.c.c.CoreListenerRegistrar : Registration Bot: code=2385607214, name=1, level=1

**Comment by Chowhound-ch** [comment]
还有，刚注意到target文件夹里的.bot文件一直标红，是不是这方面的问题

**Comment by ForteScarlet** [comment]
提供一下你的配置文件内容

**Comment by Chowhound-ch** [comment]
你是说配置账号密码的simbot.yml吗，我这个文件是空白的，账号密码放在.bot文件里

**Comment by ForteScarlet** [comment]
就是.bot文件

**Comment by Chowhound-ch** [comment]
code=2385607214
password=xxxxxxxxx

**Comment by Chowhound-ch** [comment]
而且我现在没写多少内容，程序跑起来提示一个ERROR之后好像还能正常收发消息

**Comment by ForteScarlet** [comment]
如果能正常收发消息那可能是mirai的内部错误，可以考虑更新版本，或者暂时无视。

**Comment by Chowhound-ch** [comment]
okok，谢谢大佬解答
