### ISSUE TITLE
BUG: 登录失败后mirai已经Bot close 但是OriginBotManager未清理

### ISSUE THREAD

**Issue by Lei0917** [ForteScarlet/simpler-robot#270]
### 问题描述

登录失败后mirai已经Bot close 但是OriginBotManager未清理 导致登录失败后账号无法再次注册bot

### 版本号

v3

### 相关日志

```Text
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2295049507), code=1, title=登录失败, message=帐号或密码错误，请重新输入。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more
	Suppressed: java.util.concurrent.CancellationException: Bot closed
		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
		at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
		at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:80)
		at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
		at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
		... 4 more
```

**Comment by ForteScarlet** [comment]
<https://github.com/simple-robot/simbot-component-mirai/issues/20>
