### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by BigOrange00** [ForteScarlet/simpler-robot#276]
### 疑问描述

2022-05-15 09:20:48.321  INFO 26652 --- [atcher-worker-1] l.f.s.component.mirai.bot.2178230595     : Loaded account secrets from local cache.
2022-05-15 09:20:48.323  INFO 26652 --- [atcher-worker-1] l.f.s.component.mirai.net.2178230595     : ECDH key is valid.
2022-05-15 09:20:48.533  INFO 26652 --- [atcher-worker-1] l.f.s.component.mirai.bot.2178230595     : Saved account secrets to local cache for fast login.
2022-05-15 09:20:48.681  INFO 26652 --- [atcher-worker-1] l.f.s.component.mirai.bot.2178230595     : Login successful.
2022-05-15 09:20:48.681  INFO 26652 --- [ntLoopGroup-2-3] l.f.s.component.mirai.net.2178230595     : Server time updated, serverTime: 1652577648, diff: 0ms=0.0s
2022-05-15 09:20:48.687  INFO 26652 --- [atcher-worker-3] l.f.s.component.mirai.net.2178230595     : Syncing friend message history...
2022-05-15 09:20:48.696  INFO 26652 --- [atcher-worker-1] l.f.s.component.mirai.net.2178230595     : Start loading friend list...
2022-05-15 09:20:48.696  INFO 26652 --- [atcher-worker-5] l.f.s.component.mirai.net.2178230595     : Start loading stranger list...
2022-05-15 09:20:48.722  INFO 26652 --- [atcher-worker-5] l.f.s.component.mirai.net.2178230595     : Successfully loaded stranger list: 0 in total
2022-05-15 09:20:48.777  INFO 26652 --- [atcher-worker-5] l.f.s.component.mirai.net.2178230595     : Online OtherClients: mirai(IOS)
2022-05-15 09:20:48.779  INFO 26652 --- [atcher-worker-5] l.f.s.component.mirai.net.2178230595     : Start loading group list...
2022-05-15 09:20:48.825  INFO 26652 --- [atcher-worker-5] l.f.s.component.mirai.net.2178230595     : Successfully loaded friend list: 4 in total
2022-05-15 09:20:48.843  INFO 26652 --- [atcher-worker-4] l.f.s.component.mirai.net.2178230595     : Syncing friend message history: Success.
2022-05-15 09:20:49.127  INFO 26652 --- [atcher-worker-1] l.f.s.component.mirai.net.2178230595     : Successfully loaded group list: 2 in total.
2022-05-15 09:20:49.135  INFO 26652 --- [atcher-worker-4] l.f.s.component.mirai.net.2178230595     : Scheduled key refresh in 23h 55min 0.0s.
2022-05-15 09:20:49.135  INFO 26652 --- [atcher-worker-2] l.f.s.component.mirai.net.2178230595     : Scheduled refresh login session in 19d 23h 55min 0.0s.
2022-05-15 09:20:49.137  INFO 26652 --- [           main] l.f.s.component.mirai.bot.2178230595     : Bot login successful.
2022-05-15 09:20:49.156 DEBUG 26652 --- [           main] l.f.s.c.c.CoreListenerRegistrar          : Start register listeners.
2022-05-15 09:20:49.159 DEBUG 26652 --- [           main] l.f.s.c.c.CoreListenerRegistrar          : Starter register listeners by love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar@11d0925.
2022-05-15 09:20:49.160  INFO 26652 --- [           main] .f.s.c.c.CoreMethodPostListenerRegistrar : Ready to register method listeners.
2022-05-15 09:20:49.160 DEBUG 26652 --- [           main] .f.s.c.c.CoreMethodPostListenerRegistrar : Number of beans to be scanned: 146
2022-05-15 09:20:49.282 DEBUG 26652 --- [           main] .f.s.c.c.CoreMethodPostListenerRegistrar : Cannot get type class org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$ClassProxyingConfiguration$$Lambda$250/5668466 functions, skip.

kotlin.reflect.jvm.internal.KotlinReflectionInternalError: Unresolved class: class org.springframework.boot.autoconfigure.aop.AopAutoConfiguration$ClassProxyingConfiguration$$Lambda$250/5668466
	at kotlin.reflect.jvm.internal.KClassImpl.reportUnresolvedClass(KClassImpl.kt:325) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl.access$reportUnresolvedClass(KClassImpl.kt:44) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:56) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:182) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl.getMemberScope$kotlin_reflection(KClassImpl.kt:191) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:162) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$declaredNonStaticMembers$2.invoke(KClassImpl.kt:47) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDeclaredNonStaticMembers(KClassImpl.kt) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:171) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allNonStaticMembers$2.invoke(KClassImpl.kt:47) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllNonStaticMembers(KClassImpl.kt) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allMembers$2.invoke(KClassImpl.kt:177) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data$allMembers$2.invoke(KClassImpl.kt:47) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getAllMembers(KClassImpl.kt) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.jvm.internal.KClassImpl.getMembers(KClassImpl.kt:195) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.reflect.full.KClasses.getFunctions(KClasses.kt:90) ~[kotlin-reflect-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar$registerListenerFunctions$2.invoke(CoreMethodPostListenerRegistrar.kt:103) [core-2.3.4.jar:na]
	at love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar$registerListenerFunctions$2.invoke(CoreMethodPostListenerRegistrar.kt:94) [core-2.3.4.jar:na]
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315) [kotlin-stdlib-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303) [kotlin-stdlib-1.4.30.jar:1.4.30-release-302 (1.4.30)]
	at love.forte.simbot.core.configuration.CoreMethodPostListenerRegistrar.registerListenerFunctions(CoreMethodPostListenerRegistrar.kt:166) [core-2.3.4.jar:na]
	at love.forte.simbot.core.configuration.CoreListenerRegistrar.registerListeners(CoreListenerRegistrar.kt:55) [core-2.3.4.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at love.forte.common.ioc.MethodDependPass.invoke(DependPass.kt:76) [ioc-1.0.7.jar:na]
	at love.forte.common.ioc.DependCenter.init(DependCenter.kt:108) [ioc-1.0.7.jar:na]
	at love.forte.simbot.core.SimbotApp.initDependCenter(SimbotApp.kt:434) [core-2.3.4.jar:na]
	at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:279) [core-2.3.4.jar:na]
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:509) [core-2.3.4.jar:na]
	at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt) [core-2.3.4.jar:na]
	at love.forte.simbot.spring.autoconfigure.SimbotAppConfiguration.simbotApp(SimbotAppConfiguration.java:77) [core-spring-boot-starter-2.3.4.jar:na]
	at love.forte.simbot.spring.autoconfigure.SimbotAppConfiguration$$EnhancerBySpringCGLIB$$5a9b7606.CGLIB$simbotApp$0(<generated>) [core-spring-boot-starter-2.3.4.jar:na]
	at love.forte.simbot.spring.autoconfigure.SimbotAppConfiguration$$EnhancerBySpringCGLIB$$5a9b7606$$FastClassBySpringCGLIB$$34e4e7a4.invoke(<generated>) [core-spring-boot-starter-2.3.4.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) [spring-core-5.3.7.jar:5.3.7]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) [spring-context-5.3.7.jar:5.3.7]
	at love.forte.simbot.spring.autoconfigure.SimbotAppConfiguration$$EnhancerBySpringCGLIB$$5a9b7606.simbotApp(<generated>) [core-spring-boot-starter-2.3.4.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$176/24469915.getObject(Unknown Source) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$176/24469915.getObject(Unknown Source) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$176/24469915.getObject(Unknown Source) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) [spring-beans-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) [spring-context-5.3.7.jar:5.3.7]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) [spring-boot-2.5.0.jar:2.5.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) [spring-boot-2.5.0.jar:2.5.0]
	at simbot.example.SimbotExampleApplication.main(SimbotExampleApplication.java:18) [classes/:na]

**Comment by BigOrange00** [comment]
不影响运行,就是想请教一下大佬这个是什么意思

**Comment by ForteScarlet** [comment]
这是debug日志，如果不想查看可以关闭debug级别日志输出。
