### ISSUE TITLE
[BUG] 根据微信群号获取群信息异常

### ISSUE THREAD

**Issue by JingQingQwQ** [ForteScarlet/simpler-robot#35]
version: 2.0.0-BETA.6
java: 8_261

module: 可爱猫-httpapi

## 问题描述
根据群号获取群成员异常

## 相关日志

https://paste.ubuntu.com/p/2RTJbb62gg/

## 复现方式

```java
@Listen(GroupMsg.class)
    public void testGroup(GroupMsg msg, MsgSender sender) {
        System.out.println("收到群消息:" + msg.getMsg());

        System.out.println(sender.GETTER.getGroupInfo(msg));

        for (GroupMemberInfo groupMemberInfo : sender.GETTER.getGroupMemberList(msg)) {
            System.out.println(groupMemberInfo);
        }
```

**Comment by ForteScarlet** [comment]
```
eventType: EventGroupMsg
收到群消息:1
[2021-01-06T15:41:28.725]-[ERROR] |          com.jingqingg.Listen.test.testGroup : Listener execution exception: 
java.lang.StackOverflowError
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
	at love.forte.simbot.api.sender.Getter.getGroupInfo(Getter.kt:105)
```
