### ISSUE TITLE
新版本挂起函数运行报错

### ISSUE THREAD

**Issue by Chenyuxin221** [ForteScarlet/simpler-robot#406]
### 版本号

v3.0.0-beta-RC.1

### 附加版本

simbot-component-mirai-boot:v3.0.0.0-beta-M1

### 问题描述

运行时，挂起的监听函数，无法执行

### 复现方式

@Listener
suspend fun MessageEvent.repeat(){

}

### 相关日志

```Text
love.forte.simbot.event.EventListenerProcessingException: love.forte.simboot.listener.BindException: Parameter(#2) [parameter #2 arg1 of fun com.huahua.robot.listener.`Listener$$EnhancerBySpringCGLIB$$c8c7dd68`.repeat(love.forte.simbot.event.MessageEvent!, (kotlin.coroutines.Continuation<(raw) kotlin.Any?>..kotlin.coroutines.Continuation<kotlin.Nothing>?)): kotlin.Any!] has no binder.
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker.invoke(SimpleEventListenerManagerImpl.kt:369) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$doInvoke$2$1$1.invokeSuspend(SimpleEventListenerManagerImpl.kt:215) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.6.21.jar:1.6.21-release-334(1.6.21)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: love.forte.simboot.listener.BindException: Parameter(#2) [parameter #2 arg1 of fun com.huahua.robot.listener.`Listener$$EnhancerBySpringCGLIB$$c8c7dd68`.fakePictures(love.forte.simbot.event.MessageEvent!, (kotlin.coroutines.Continuation<(raw) kotlin.Any?>..kotlin.coroutines.Continuation<kotlin.Nothing>?)): kotlin.Any!] has no binder.
	at love.forte.simboot.core.listener.EmptyBinder$resultProvider$3.invoke-d1pmJ48(KFunctionListenerProcessor.kt:500) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.EmptyBinder$resultProvider$3.invoke(KFunctionListenerProcessor.kt:499) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.EmptyBinder.arg-gIAlu-s(KFunctionListenerProcessor.kt:505) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.listener.FunctionalBindableEventListener.invokeCall(FunctionalBindableEventListener.kt:101) ~[simboot-api-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.listener.FunctionalBindableEventListener.invoke$suspendImpl(FunctionalBindableEventListener.kt:95) ~[simboot-api-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.listener.FunctionalBindableEventListener.invoke(FunctionalBindableEventListener.kt) ~[simboot-api-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2$2.invokeSuspend(KFunctionListenerProcessor.kt:135) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2$2.invoke(KFunctionListenerProcessor.kt) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2$2.invoke(KFunctionListenerProcessor.kt) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:169) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:163) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2.invokeSuspend(KFunctionListenerProcessor.kt:134) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2.invoke(KFunctionListenerProcessor.kt) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2.invoke(KFunctionListenerProcessor.kt) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerProxy.invoke(SimpleListenerProxy.kt:75) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2$1.invokeSuspend(SimpleEventListenerManagerImpl.kt:322) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2$1.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2$1.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:169) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:163) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2.invokeSuspend(SimpleEventListenerManagerImpl.kt:321) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:169) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:163) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker._init_$runner(SimpleEventListenerManagerImpl.kt:319) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker._init_$suspendFunctionRunner(SimpleEventListenerManagerImpl.kt:347) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker.access$_init_$suspendFunctionRunner(SimpleEventListenerManagerImpl.kt:286) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$functionRunner$2.invokeSuspend(SimpleEventListenerManagerImpl.kt:354) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$functionRunner$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$functionRunner$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker.invoke(SimpleEventListenerManagerImpl.kt:363) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	... 6 common frames omitted
```

**Comment by ForteScarlet** [comment]
通过下述代码未复现成功
```kotlin
@Component
class MyListenerConfiguration {
    private val logger = LoggerFactory.getLogger(MyListenerConfiguration::class.java)
    @Listener
    suspend fun MessageEvent.myListener() {
        logger.info("ON EVENT: {}", this)
    }
}
```
请检查是否会由其他原因导致，并提供更完整的代码信息以及依赖信息。

**Comment by Chenyuxin221** [comment]
经检查或是自定义监听器因版本更新原因问题无法使用，目前尚未查明具体原因
代码如下：
```
@Component
@Aspect
class ListenerAspect {

    /**
     * 拦截监听器方法
     */
    @Around("@annotation(com.huahua.robot.core.annotation.RobotListen) && @annotation(annotation)) && args(continuation)")
    fun ProceedingJoinPoint.doAroundAdvice(annotation: RobotListen): Any? {
        val start = System.currentTimeMillis()
        val event = args.find { it is Event } ?: return proceed()
        fun proceedSuccess(): Any? {
            logger {
                -"执行了监听器${signature.name}(${annotation.desc})"
                -("执行拦截器耗时: " + (System.currentTimeMillis() - start))
            }

            return proceed()
        }

        fun proceedFailed(tip: String) {
            logger {
                -"执行监听器${signature.name}(${annotation.desc})失败, $tip"
                -("执行拦截器耗时: " + (System.currentTimeMillis() - start))
            }
            return
        }

        if (event is GroupMessageEvent) {
            val group = runBlocking { event.group() }
            val author = runBlocking { event.author() }
            val role = runBlocking { author.roles.toList()[0] }
            val botPermission = runBlocking { group.member(event.bot.id)?.roles?.toList()?.get(0)}
                // 判断是否开机
            if (annotation.isBoot && !RobotCore.BOOT_MAP.getOrDefault(group.id.toString(), false)) {
                return proceedFailed("当前群未开机")
            }
            // 判断是否有权限
            if (
                annotation.permission != RobotPermission.MEMBER &&
                annotation.permission > role && !RobotCore.isBotAdministrator(author.id.toString())
            ) {
                if (annotation.noPermissionTip.isNotBlank()) {
                    Sender.sendGroupMsg(group, annotation.noPermissionTip)
                    return proceedFailed("权限不足")
                }
            }
            // 判断机器人是否有执行权限
            if (botPermission == null ||
                annotation.permissionsRequiredByTheRobot > botPermission &&
                annotation.permission != RobotPermission.MEMBER
            ) {
                if (annotation.botNotHavePermissionTip.isNotBlank()) {
                    Sender.sendGroupMsg(group, annotation.botNotHavePermissionTip)
                    return proceedFailed("机器人权限不足")
                }
            }
        }
        return proceedSuccess()
    }
}
```

**Comment by ForteScarlet** [comment]
Spring的AOP对**挂起函数**的支持并不好，这可能会导致很多问题。
部分参考：
- https://github.com/spring-projects/spring-security/issues/11335
- https://github.com/spring-projects/spring-framework/issues/22462

如果希望对所有的监听函数进行拦截，可以参考：
```kotlin
/**
 * 实现 [EventListenerInterceptor], 拦截每一个将要执行的 **监听函数**。
 * 如果希望只针对整体的事件流程拦截，使用 [EventProcessingInterceptor].
 */
@Component
class MyListenerInterceptor : EventListenerInterceptor {
    private val logger = LoggerFactory.getLogger(MyListenerInterceptor::class.java)
    override suspend fun intercept(context: EventListenerInterceptor.Context): EventResult {
        val event = context.eventContext.event
        if (event is GroupMessageEvent) {
            logger.info("拦截到监听函数: {}", context.listener)
            // do...
            // 返回context的真正处理结果，可理解为'放行'之意
            return context.proceed()
        }
        
        // 直接返回结果，而不执行context的处理，可理解为'拦截'之意
        // 此处返回一个 'invalid', 代表无效结果。
        return EventResult.invalid()
    }
}
```

如果希望能获取到注册的监听函数原本的 `KFunction` 对象（例如用来获取注解等行为），参考：

```kotlin
@Component
class MyListenerInterceptor : EventListenerInterceptor {
    private val logger = LoggerFactory.getLogger(MyListenerInterceptor::class.java)
    override suspend fun intercept(context: EventListenerInterceptor.Context): EventResult {
        // 被拦截的监听函数的原始function。如果不存在或不支持则抛出 NoSuchElementException
        val function = context.listener.rawFunction
    
        // 被拦截的监听函数的原始function。如果不存在或不支持则得到null
        val functionOrNull = context.listener.rawFunctionOrNull
        
       logger.info("被拦截的监听函数Function: {}", functionOrNull)

        return context.proceed()
    }
}
```
