### ISSUE TITLE
无法解除禁言

### ISSUE THREAD

**Issue by Chenyuxin221** [ForteScarlet/simpler-robot#411]
### 版本号

v3.0.0-beta-RC.1

### 附加版本

simbot-component-mirai-boot:v3.0.0.0-beta-M1

### 问题描述

新版本无法对禁言用户解除禁言

### 复现方式

```
@Listener
@Filter("解", matchType = MatchType.TEXT_STARTS_WITH)
    suspend fun GroupMessageEvent.unBan() {
        messageContent.messages.forEach {
            if (it is At) {
                group().member(it.target)!!.unmute()
            }
        }
    }
```

### 相关日志

```Text
love.forte.simbot.event.EventListenerProcessingException: java.lang.IllegalArgumentException: durationSeconds must greater than zero
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker.invoke(SimpleEventListenerManagerImpl.kt:367) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$doInvoke$2$1$1.invokeSuspend(SimpleEventListenerManagerImpl.kt:215) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.6.21.jar:1.6.21-release-334(1.6.21)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.5.2.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.IllegalArgumentException: durationSeconds must greater than zero
	at net.mamoe.mirai.internal.contact.NormalMemberImpl.mute(NormalMemberImpl.kt:132) ~[mirai-core-jvm-2.11.1.jar:2.11.1]
	at love.forte.simbot.component.mirai.MiraiMember.unmute$suspendImpl(MiraiMember.kt:182) ~[simbot-component-mirai-core-3.0.0.0-beta-M1.jar:na]
	at love.forte.simbot.component.mirai.MiraiMember.unmute(MiraiMember.kt) ~[simbot-component-mirai-core-3.0.0.0-beta-M1.jar:na]
	at com.huahua.robot.listener.grouplistener.GroupMangerListener.unBan$suspendImpl(GroupMangerListener.kt:88) ~[classes/:na]
	at com.huahua.robot.listener.grouplistener.GroupMangerListener.unBan(GroupMangerListener.kt) ~[classes/:na]
	at com.huahua.robot.listener.grouplistener.GroupMangerListener$$FastClassBySpringCGLIB$$1cf0cf1d.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.19.jar:5.3.19]
	at com.huahua.robot.core.common.ListenerAspect.doAroundAdvice$proceedSuccess(ListenerAspect.kt:37) ~[classes/:na]
	at com.huahua.robot.core.common.ListenerAspect.doAroundAdvice(ListenerAspect.kt:78) ~[classes/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.19.jar:5.3.19]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.19.jar:5.3.19]
	at com.huahua.robot.listener.grouplistener.GroupMangerListener$$EnhancerBySpringCGLIB$$2b618eef.unBan(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97) ~[kotlin-reflect-1.6.21.jar:1.6.21-release-334(1.6.21)]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113) ~[kotlin-reflect-1.6.21.jar:1.6.21-release-334(1.6.21)]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108) ~[kotlin-reflect-1.6.21.jar:1.6.21-release-334(1.6.21)]
	at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:56) ~[kotlin-reflect-1.6.21.jar:1.6.21-release-334(1.6.21)]
	at love.forte.simboot.listener.FunctionalBindableEventListener.invokeCall(FunctionalBindableEventListener.kt:110) ~[simboot-api-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.listener.FunctionalBindableEventListener.invoke$suspendImpl(FunctionalBindableEventListener.kt:95) ~[simboot-api-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.listener.FunctionalBindableEventListener.invoke(FunctionalBindableEventListener.kt) ~[simboot-api-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.DelegatedEventListener.invoke(SimpleListenerProxy.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2$2.invokeSuspend(KFunctionListenerProcessor.kt:135) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2$2.invoke(KFunctionListenerProcessor.kt) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2$2.invoke(KFunctionListenerProcessor.kt) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:169) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:163) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2.invokeSuspend(KFunctionListenerProcessor.kt:134) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2.invoke(KFunctionListenerProcessor.kt) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simboot.core.listener.KFunctionListenerProcessor$process$2.invoke(KFunctionListenerProcessor.kt) ~[simboot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerProxy.invoke(SimpleListenerProxy.kt:75) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2$1.invokeSuspend(SimpleEventListenerManagerImpl.kt:322) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2$1.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2$1.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:169) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:163) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2.invokeSuspend(SimpleEventListenerManagerImpl.kt:321) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$runner$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:169) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.EventListenerDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:163) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker._init_$runner(SimpleEventListenerManagerImpl.kt:319) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker._init_$suspendFunctionRunner(SimpleEventListenerManagerImpl.kt:347) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker.access$_init_$suspendFunctionRunner(SimpleEventListenerManagerImpl.kt:286) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$functionRunner$2.invokeSuspend(SimpleEventListenerManagerImpl.kt:354) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$functionRunner$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker$functionRunner$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$ListenerInvoker.invoke(SimpleEventListenerManagerImpl.kt:363) ~[simbot-core-3.0.0-beta-RC.1.jar:na]
	... 6 common frames omitted
```

**Comment by ForteScarlet** [comment]
追踪 https://github.com/simple-robot/simbot-component-mirai/issues/58 ，当前 issue 将会关闭。
