### ISSUE TITLE
接收的到消息但是没法发送消息

### ISSUE THREAD

**Issue by Uni12321** [ForteScarlet/simpler-robot#592]
### 版本号

3.0.0-M6

### 附加版本

<simbot.version>3.0.0-M6</simbot.version>
        <simbot-component-mirai.version>3.0.0.0-M4</simbot-component-mirai.version>

### 选择此问题涉及的编程语言

Java

### 选择此问题涉及的组件库

mirai

### 问题描述

```java
    @Listener
    @Filter(value = "测试" , matchType = MatchType.TEXT_EQUALS)
    public void Enroll(GroupMessageEvent event) {
        try {
            event.replyAsync("测试测试测试");
        } catch (Exception e) {
            event.replyAsync("测试测试测试");
        }
    }
```

这里是部分代码块  我编写此测试代码 能接受到用户发来的消息 但是没回复消息 日志没有报错
```java
    @Listener
    @ContentTrim
    @Filter(value = "/青年大学习")
    public void getBigLearning(GroupMessageEvent event) throws MalformedURLException {
        MessagesBuilder builder = new MessagesBuilder();
        data gsonData = new Gson().fromJson(HttpUtils.get(getLear()), data.class);
        builder.at(event.getAuthor().getId());
        data.DataDTO gsonDataData = gsonData.getData();
        builder.text("\n标题: " + gsonDataData.getTitle() + "\n");
        builder.text("主页: " + gsonDataData.getUrl() + "\n");
        builder.image(Resource.of(new URL(gsonDataData.getImg())));
        event.getSource().sendBlocking(builder.build());
    }
```
这部分代码块会导致报错  说消息发不出去

### 复现方式

使用的springboot版本的为3.0.2 jdk版本为17.0.5
下面是所使用的的依赖包
```xml
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <version>3.0.2</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/love.forte.simbot.boot/simboot-core-springboot-starter -->
<!--        simbot-->
        <dependency>
            <groupId>love.forte.simbot.boot</groupId>
            <artifactId>simboot-core-spring-boot-starter</artifactId>
            <version>${simbot.version}</version>
        </dependency>
<!--        mirai组件-->
        <dependency>
            <groupId>love.forte.simbot.component</groupId>
            <artifactId>simbot-component-mirai-core</artifactId>
            <version>${simbot-component-mirai.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.5</version>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.10</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>compile</scope>
        </dependency>

        <!-- HttpClinet 核心包 -->
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.14</version>
        </dependency>
        <!-- HttpClinet 请求时，涉及文件上传需要的包 -->
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.5.14</version>
        </dependency>
<!--        MySQL配置文件-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.30</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>5.0.0-alpha.11</version>
        </dependency>
    </dependencies>
```

### 相关日志

```Text
2023-02-13T13:56:02.466+08:00  INFO 23740 --- [        task-39] org.Simbot.listens.ListenGroup           : 群: 测试机器人(476942752)		成员: 祺诺(1053557904)
2023-02-13T13:56:02.466+08:00  INFO 23740 --- [        task-39] org.Simbot.utils.Msg                     : [文本消息: /青年大学习 ]
2023-02-13T13:56:03.609+08:00  WARN 23740 --- [        task-39] o.a.h.c.protocol.ResponseProcessCookies  : Invalid cookie header: "Set-Cookie: https_waf_cookie=4dc13be2-883c-420c9dcdf4a5453a46f56a36f86b942f0563; Expires=1676274963; Path=/; Secure; HttpOnly". Invalid 'expires' attribute: 1676274963
2023-02-13T13:56:04.007+08:00 ERROR 23740 --- [        task-39] l.f.s.c.e.SimpleEventListenerManagerImpl : Listener [ProxiedEventListener(DelegatedListener(KFunctionEventListener(isSuspend=false, targets=[EventKey(id=api.group_message)], binders=[love.forte.simboot.core.listener.MergedBinder@7906be8e, love.forte.simboot.core.listener.MergedBinder@1e63e4cb], caller=fun org.Simbot.plugins.youthlearning.getLearning.getBigLearning(love.forte.simbot.event.GroupMessageEvent!): kotlin.Unit)))] process failed: java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)

love.forte.simbot.event.EventListenerProcessingException: java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
	at love.forte.simbot.core.event.ListenerInvoker.invoke(SimpleEventListenerManagerImpl.kt:468) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$doInvoke$2$1$1.invokeSuspend(SimpleEventListenerManagerImpl.kt:316) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$doInvoke$2$1$1.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$doInvoke$2$1$1.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.core.event.EventProcessingDirectInterceptEntrance.doIntercept(EventInterceptEntrance.kt:120) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$doInvoke$2.invokeSuspend(SimpleEventListenerManagerImpl.kt:310) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$doInvoke$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl$doInvoke$2.invoke(SimpleEventListenerManagerImpl.kt) ~[simbot-core-3.0.0-M6.jar:na]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl.doInvoke(SimpleEventListenerManagerImpl.kt:308) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.core.event.SimpleEventListenerManagerImpl.push(SimpleEventListenerManagerImpl.kt:295) ~[simbot-core-3.0.0-M6.jar:na]
	at love.forte.simbot.component.mirai.internal.MiraiBotImplKt$registerEvents$1$invokeSuspend$$inlined$doHandler$3.invokeSuspend(MiraiBotImpl.kt:626) ~[simbot-component-mirai-core-3.0.0.0-M4.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.20.jar:1.7.20-release-201(1.7.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:150) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:50) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.20.jar:1.7.20-release-201(1.7.20)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.7.20.jar:1.7.20-release-201(1.7.20)]
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1413) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:102) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:160) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.4.jar:2.13.4]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.20.jar:1.7.20-release-201(1.7.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	... 1 common frames omitted
```

**Comment by ForteScarlet** [comment]
参考 https://github.com/mamoe/mirai/issues/2127 ，手动登录账号检查是否存在类似的封禁情况

**Comment by Uni12321** [comment]
手动登录后 未发现封禁 但是重新验证登录后 机器人能正常发送消息了
