### ISSUE TITLE
code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录。

### ISSUE THREAD

**Issue by Teylusu** [ForteScarlet/simpler-robot#614]
### 版本号

3.0.0-RC.3

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

mirai (QQ)

### 问题描述

Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(*********), code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331) ~[mirai-core-jvm-2.14.0.jar!/:2.14.0]
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[mirai-core-jvm-2.14.0.jar!/:2.14.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.6.21.jar!/:1.6.21-release-334(1.6.21)]
	... 8 common frames omitted

### 复现方式

禁止登陆

**Comment by ForteScarlet** [comment]
https://github.com/mamoe/mirai/issues/2552

可能是新出现的风控类型。等待并关注mirai社区的相关问题

**Comment by ElementQi** [comment]
上面说的应该是协议是`ANDROID_WATCH`的情况，我把它再换成`ANDROID_PAD`话（`PHONE`也一样），出现了以下情况
```
2023-03-08 00:52:22 I/main: Auto-login 7*******8, protocol: ANDROID_PAD, heartbeatStrategy: STAT_HB
2023-03-08 00:52:26 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(7*******8), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(7*******8), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

这个情况就是我之前在`win10PC`上登录的时候遇见的，版本太低了（但是用大号能登录，但是小号就不行，一登录就提示我版本过低，什么代码00020之类的，记不清楚了），然后更新了一下版本就可以登录了。

我猜测应mirai社区应该需要更新一下这些qq登录设备`protocol`的版本？（本人不太了解）

**Comment by Enderman-Teleporting** [comment]
我设置的protocol是MACOS,出现了“网络不稳定”的问题

**Comment by ForteScarlet** [comment]
参考 [discussions#108](https://github.com/orgs/simple-robot/discussions/108)

**Comment by vudsen** [comment]
从release里面下jar包丢项目里面：https://github.com/cssxsh/fix-protocol-version/tree/main

然后主类这样配置:
```kotlin
import xyz.cssxsh.mirai.tool.FixProtocolVersion

fun main(args: Array<String>) {
    FixProtocolVersion.update()
    val application = runApplication<QQBotApplication>(*args)
}
```

我用的`MACOS`协议，能登录上去

**Comment by ZeyuanGuo** [comment]
> 从release里面下jar包丢项目里面：https://github.com/cssxsh/fix-protocol-version/tree/main
> 
> 然后主类这样配置:
> 
> ```kotlin
> import xyz.cssxsh.mirai.tool.FixProtocolVersion
> 
> fun main(args: Array<String>) {
>     FixProtocolVersion.update()
>     val application = runApplication<QQBotApplication>(*args)
> }
> ```
> 
> 我用的`MACOS`协议，能登录上去

刚把各种协议和device换了一轮 45 237 235 238都见了个遍，这个macos的报45，换成大号也报238，按理说大号应该没风控不会有这个啊...已经在考虑开个新号试试了（

watch的协议用这个获取device的软件，能扫码登陆上，似乎挺有希望的 [MrXiaoM/Aoki](https://github.com/MrXiaoM/Aoki) 

看着好像mirai最近的2.15有扫码的方式？`simbot-component-mirai`写的对应mirai还是2.14，不知道这里的能不能更新扫码方式的支持看有没有救

（另外[v3.0.0.0-beta.6](https://github.com/simple-robot/simbot-component-mirai/releases/tag/v3.0.0.0-beta.6)之后版本在阿里云的maven上面就没有了 有点寄）

**Comment by ForteScarlet** [comment]
@112292454 mirai的2.15正式发布后这边才会更新，以及不要用阿里云的maven仓库，直接用中央仓库。
