### ISSUE TITLE
调用QQ频道组件下的发送帖子API时出现异常

### ISSUE THREAD

**Issue by Flock-YT** [ForteScarlet/simpler-robot#675]
### 版本号

Simbot版本：3.0.0   QQ频道组件版本：3.0.0-alpha.7

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

QQ频道

### 问题描述

调用QQ频道组件的发送消息与发送帖子的API时均出现这个报错。
![image](https://github.com/simple-robot/simpler-robot/assets/109157284/ea2b502a-e882-48c9-b703-1e684c1bb5cf)

### 复现方式

`PublishThreadApi publishThreadApi = PublishThreadApi.createText(”频道ID“, "Test Title" , "Test Content");
publishThreadApi.doRequestRawBlocking("HttpClient" , "服务器URL" , "Token");`

### 相关日志

```Text
java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class love.forte.simbot.qguild.api.forum.PublishThreadApi$Body, with Content-Type: application/json.

If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.

	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invokeSuspend(HttpSend.kt:88)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(HttpSend.kt)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(HttpSend.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:130)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invokeSuspend(HttpRequestLifecycle.kt:38)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(HttpRequestLifecycle.kt)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(HttpRequestLifecycle.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.client.HttpClient.execute$ktor_client_core(HttpClient.kt:191)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:108)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:47)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:62)
	at love.forte.simbot.qguild.api.QQGuildApiKt.request0(QQGuildApi.kt:372)
	at love.forte.simbot.qguild.api.QQGuildApiKt.access$request0(QQGuildApi.kt:1)
	at love.forte.simbot.qguild.api.QQGuildApi.doRequestRaw$suspendImpl(QQGuildApi.kt:206)
	at love.forte.simbot.qguild.api.QQGuildApi.doRequestRaw(QQGuildApi.kt)
	at love.forte.simbot.qguild.api.PlatformQQGuildApi$doRequestRawBlocking$1.invokeSuspend(QQGuildApi.jvm.kt:134)
	at |b|b|b(Coroutine boundary.|b(|b)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:130)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invokeSuspend(HttpRequestLifecycle.kt:38)
	at io.ktor.client.HttpClient.execute$ktor_client_core(HttpClient.kt:191)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:108)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:47)
	at love.forte.simbot.qguild.api.QQGuildApi.doRequestRaw$suspendImpl(QQGuildApi.kt:206)
	at love.forte.simbot.qguild.api.PlatformQQGuildApi$doRequestRawBlocking$1.invokeSuspend(QQGuildApi.jvm.kt:134)
Caused by: java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class love.forte.simbot.qguild.api.forum.PublishThreadApi$Body, with Content-Type: application/json.

If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invokeSuspend(HttpSend.kt:88)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(HttpSend.kt)
	at io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(HttpSend.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:88)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:130)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
	at io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invokeSuspend(HttpRequestLifecycle.kt:38)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(HttpRequestLifecycle.kt)
	at io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(HttpRequestLifecycle.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.client.HttpClient.execute$ktor_client_core(HttpClient.kt:191)
	at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:108)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:47)
	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:62)
	at love.forte.simbot.qguild.api.QQGuildApiKt.request0(QQGuildApi.kt:372)
	at love.forte.simbot.qguild.api.QQGuildApiKt.access$request0(QQGuildApi.kt:1)
	at love.forte.simbot.qguild.api.QQGuildApi.doRequestRaw$suspendImpl(QQGuildApi.kt:206)
	at love.forte.simbot.qguild.api.QQGuildApi.doRequestRaw(QQGuildApi.kt)
	at love.forte.simbot.qguild.api.PlatformQQGuildApi$doRequestRawBlocking$1.invokeSuspend(QQGuildApi.jvm.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by ForteScarlet** [comment]
临时解决办法：在使用的 `HttpClient` 中安装 `ContentNegotiation` 插件，例如：
```java
HttpClient client = HttpClientJvmKt.HttpClient(conf -> {
   conf.install(ContentNegotiation.Plugin, serConf -> {
       JsonSupportKt.json(
               serConf,
               JsonSupportKt.getDefaultJson(),
               ContentType.Application.INSTANCE.getJson()
       );
       return Unit.INSTANCE;
   });
    return Unit.INSTANCE;
});
```

**Comment by ForteScarlet** [comment]
或者使用 `love.forte.simbot.qguild.BotRequestUtil.requestBlocking(bot, api)` 来进行API请求：
```java
QGBot qgBot = ...;
PublishThreadApi publishThreadApi = PublishThreadApi.createText(channelId, "Test Title" , "Test Content");
BotRequestUtil.requestBlocking(qgBot.getSource(), publishThreadApi);
```
