### ISSUE TITLE
KOOK机器人被踢出服务器后会报错

### ISSUE THREAD

**Issue by axiangcoding** [ForteScarlet/simpler-robot#728]
### 版本号

v3.2.0

### 附加版本

love.forte.simbot.component:simbot-component-kook-core:3.0.0.0-alpha.7

### 涉及的编程语言

Java

### 项目构建工具

Gradle

### 涉及的组件库

KOOK

### 问题描述

在KOOK将机器人踢出服务器，会报一个错误

### 复现方式

- 踢出机器人
- 报错，但应该无影响

### 相关日志

```Text
Exception in thread "DefaultDispatcher-worker-19" love.forte.simbot.kook.api.KookApiException: code: 40000, message: 该用户不在该服务器内, api=ApiResult(code=40000, message=该用户不在该服务器内, data={}, httpStatus=200 OK, rateLimit=RateLimit(limit=120, remaining=119, reset=0, bucket=guild/user-list, isGlobalLimit=false), raw={"code":40000,"message":"该用户不在该服务器内","data":{}})
	at love.forte.simbot.kook.api.ApiResult.parseDataOrThrow(KookApiResult.kt:234)
	at love.forte.simbot.kook.api.KookApiRequest.requestData$suspendImpl(KookApiRequest.kt:292)
	at love.forte.simbot.kook.api.KookApiRequest$requestData$1.invokeSuspend(KookApiRequest.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(KookBot.FXyJ3gXVXeAEpXUv), StandaloneCoroutine{Cancelling}@701bc440, Dispatchers.Default]
```

**Comment by ForteScarlet** [comment]
本地测试暂未复现，此异常是必然产生还是偶然？可能会在什么情况下会产生？

**Comment by axiangcoding** [comment]
> 本地测试暂未复现，此异常是必然产生还是偶然？可能会在什么情况下会产生？

看起来是偶现。目前无法复现了

**Comment by axiangcoding** [comment]
问题复现，大致还原流程如下
- 打开kook软件
- 打开项目，并启动工程完成机器人初始化
- 在kook软件上，使用个人账号踢出机器人账号
- 报错同上

**Comment by ForteScarlet** [comment]
现在重构后的版本 [v3.2.0.0-alpha.8-dev.2](https://github.com/simple-robot/simbot-component-kook/releases/tag/v3.2.0.0-alpha.8-dev.2) 已经发布，可以在确认此版本的注意事项后简单的进行尝试是否还会存在此问题

**Comment by axiangcoding** [comment]
> 现在重构后的版本 [v3.2.0.0-alpha.8-dev.2](https://github.com/simple-robot/simbot-component-kook/releases/tag/v3.2.0.0-alpha.8-dev.2) 已经发布，可以在确认此版本的注意事项后简单的进行尝试是否还会存在此问题

我的ci没通过，这个包似乎有些问题？
https://github.com/axbot-dev/axbot/actions/runs/5897406284/job/15996975631?pr=218

**Comment by ForteScarlet** [comment]
此版本是重构产物，属于不兼容更新，可以从本地简单测试先看看之类的

**Comment by axiangcoding** [comment]
> 此版本是重构产物，属于不兼容更新，可以从本地简单测试先看看之类的

好
