### ISSUE TITLE
kook组件启动报错

### ISSUE THREAD

**Issue by axiangcoding** [ForteScarlet/simpler-robot#736]
### 版本号

latest

### 附加版本

love.forte.simbot.component:simbot-component-kook-core:3.2.0.0-alpha.8-dev.2

### 涉及的编程语言

Java

### 项目构建工具

Gradle

### 涉及的组件库

KOOK

### 问题描述

升级到新版本，修改成新版本对应的包名后，启动后报错

### 复现方式

修改成新版本对应的包名后，启动后报错

### 相关日志

```Text
2023-08-21T18:27:22.728+08:00  INFO 50976 --- [  restartedMain] o.a.c.c.StandardService                  : [: ] Stopping service [Tomcat]
2023-08-21T18:27:22.744+08:00  INFO 50976 --- [  restartedMain] .s.b.a.l.ConditionEvaluationReportLogger : [: ] 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-08-21T18:27:22.762+08:00 ERROR 50976 --- [  restartedMain] o.s.b.SpringApplication                  : [: ] Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simbotApplicationAfterApplication' defined in class path resource [love/forte/simboot/spring/autoconfigure/SimbotSpringBootApplicationConfiguration.class]: Failed to instantiate [love.forte.simboot.spring.autoconfigure.AutoConfigureMarker$AfterApplicationPostProcessor]: Factory method 'simbotApplicationAfterApplication' threw exception with message: Serializer for KookTempTarget can't be registered as a subclass for polymorphic serialization because its kind SEALED is not concrete. To work with multiple hierarchies, register it as a base class.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) [spring-boot-3.1.2.jar:3.1.2]
	at com.github.axiangcoding.axbot.app.AppApplication.main(AppApplication.java:13) [main/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50) [spring-boot-devtools-3.1.2.jar:3.1.2]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [love.forte.simboot.spring.autoconfigure.AutoConfigureMarker$AfterApplicationPostProcessor]: Factory method 'simbotApplicationAfterApplication' threw exception with message: Serializer for KookTempTarget can't be registered as a subclass for polymorphic serialization because its kind SEALED is not concrete. To work with multiple hierarchies, register it as a base class.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar:6.0.11]
	... 24 more
Caused by: java.lang.IllegalArgumentException: Serializer for KookTempTarget can't be registered as a subclass for polymorphic serialization because its kind SEALED is not concrete. To work with multiple hierarchies, register it as a base class.
	at kotlinx.serialization.json.internal.PolymorphismValidator.checkKind(PolymorphismValidator.kt:41) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.json.internal.PolymorphismValidator.polymorphic(PolymorphismValidator.kt:31) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.modules.SerialModuleImpl.dumpTo(SerializersModule.kt:189) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.json.JsonImpl.validateConfiguration(Json.kt:385) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.json.JsonImpl.<init>(Json.kt:379) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.json.JsonKt.Json(Json.kt:201) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.json.JsonKt.Json$default(Json.kt:197) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at love.forte.simbot.bot.JsonBotVerifyInfoDecoder$Factory.create(BotVerifyInfo.kt:420) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.bot.JsonBotVerifyInfoDecoder$Factory.create(BotVerifyInfo.kt:402) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.bot.StandardBotVerifyInfoDecoderFactory.create$default(BotVerifyInfo.kt:183) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor$config$botConfigResources$3.invoke(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:137) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor$config$botConfigResources$3.invoke(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:109) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor.config(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:142) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor.processApplication(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:55) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootApplicationConfiguration$simbotApplicationAfterApplication$1.invokeSuspend(SimbotSpringBootApplicationConfiguration.kt:130) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at love.forte.simbot.utils.DefaultRunInNoScopeBlockingStrategy.invoke(BlockingRunner.kt:423) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simbot.utils.BlockingRunnerKt.runInNoScopeBlocking(BlockingRunner.kt:496) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simbot.utils.BlockingRunnerKt.runInNoScopeBlocking$default(BlockingRunner.kt:493) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootApplicationConfiguration.simbotApplicationAfterApplication(SimbotSpringBootApplicationConfiguration.kt:129) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar:6.0.11]
	... 24 more


Process finished with exit code 1
```

**Comment by ForteScarlet** [comment]
[KOOK#106](https://github.com/simple-robot/simbot-component-kook/pull/106) 合并后应该会发布 `v3.2.0.0-alpha.8-dev.3`，届时可再做尝试

**Comment by axiangcoding** [comment]
`v3.2.0.0-alpha.8-dev.3` 依然存在报错
```log
Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-08-26T16:56:13.009+08:00 ERROR 70168 --- [  restartedMain] o.s.b.SpringApplication                  : [: ] Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'simbotApplicationAfterApplication' defined in class path resource [love/forte/simboot/spring/autoconfigure/SimbotSpringBootApplicationConfiguration.class]: Failed to instantiate [love.forte.simboot.spring.autoconfigure.AutoConfigureMarker$AfterApplicationPostProcessor]: Factory method 'simbotApplicationAfterApplication' threw exception with message: Field 'guild' is required for type with serial name 'love.forte.simbot.component.kook.bot.KookBotConfiguration.SyncPeriods', but it was missing at path: $.config.syncPeriods
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:659) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:647) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.11.jar:6.0.11]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-3.1.2.jar:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) [spring-boot-3.1.2.jar:3.1.2]
	at com.github.axiangcoding.axbot.app.AppApplication.main(AppApplication.java:13) [main/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50) [spring-boot-devtools-3.1.2.jar:3.1.2]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [love.forte.simboot.spring.autoconfigure.AutoConfigureMarker$AfterApplicationPostProcessor]: Factory method 'simbotApplicationAfterApplication' threw exception with message: Field 'guild' is required for type with serial name 'love.forte.simbot.component.kook.bot.KookBotConfiguration.SyncPeriods', but it was missing at path: $.config.syncPeriods
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar:6.0.11]
	... 24 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'guild' is required for type with serial name 'love.forte.simbot.component.kook.bot.KookBotConfiguration.SyncPeriods', but it was missing at path: $.config.syncPeriods
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:93) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at love.forte.simbot.component.kook.bot.KookBotVerifyInfoConfiguration$Config$$serializer.deserialize(KookBotVerifyInfoConfiguration.kt:95) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at love.forte.simbot.component.kook.bot.KookBotVerifyInfoConfiguration$Config$$serializer.deserialize(KookBotVerifyInfoConfiguration.kt:95) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at love.forte.simbot.component.kook.bot.KookBotVerifyInfoConfiguration$$serializer.deserialize(KookBotVerifyInfoConfiguration.kt:63) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at love.forte.simbot.component.kook.bot.KookBotVerifyInfoConfiguration$$serializer.deserialize(KookBotVerifyInfoConfiguration.kt:63) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at love.forte.simbot.bot.StandardStringFormatBotVerifyInfoDecoder.decode(BotVerifyInfo.kt:342) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.bot.StandardStringFormatBotVerifyInfoDecoder.decode(BotVerifyInfo.kt:328) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.bot.StandardSerialFormatBotVerifyInfoDecoder.decode(BotVerifyInfo.kt:321) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.bot.DecoderBotVerifyInfo.decode(BotVerifyInfos.kt:53) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.component.kook.bot.KookBotManager.register(KookBotManager.kt:112) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor.register(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:244) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor.config(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:148) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor.processApplication(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:55) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootApplicationConfiguration$simbotApplicationAfterApplication$1.invokeSuspend(SimbotSpringBootApplicationConfiguration.kt:130) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at love.forte.simbot.utils.DefaultRunInNoScopeBlockingStrategy.invoke(BlockingRunner.kt:423) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simbot.utils.BlockingRunnerKt.runInNoScopeBlocking(BlockingRunner.kt:496) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simbot.utils.BlockingRunnerKt.runInNoScopeBlocking$default(BlockingRunner.kt:493) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootApplicationConfiguration.simbotApplicationAfterApplication(SimbotSpringBootApplicationConfiguration.kt:129) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar:6.0.11]
	... 24 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'guild' is required for type with serial name 'love.forte.simbot.component.kook.bot.KookBotConfiguration.SyncPeriods', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at love.forte.simbot.component.kook.bot.KookBotConfiguration$SyncPeriods.<init>(KookBotConfiguration.kt:50) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at love.forte.simbot.component.kook.bot.KookBotConfiguration$SyncPeriods$$serializer.deserialize(KookBotConfiguration.kt:50) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at love.forte.simbot.component.kook.bot.KookBotConfiguration$SyncPeriods$$serializer.deserialize(KookBotConfiguration.kt:50) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at love.forte.simbot.component.kook.bot.KookBotVerifyInfoConfiguration$Config$$serializer.deserialize(KookBotVerifyInfoConfiguration.kt:95) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at love.forte.simbot.component.kook.bot.KookBotVerifyInfoConfiguration$Config$$serializer.deserialize(KookBotVerifyInfoConfiguration.kt:95) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:79) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at love.forte.simbot.component.kook.bot.KookBotVerifyInfoConfiguration$$serializer.deserialize(KookBotVerifyInfoConfiguration.kt:63) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at love.forte.simbot.component.kook.bot.KookBotVerifyInfoConfiguration$$serializer.deserialize(KookBotVerifyInfoConfiguration.kt:63) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107) ~[kotlinx-serialization-json-jvm-1.5.1.jar:?]
	at love.forte.simbot.bot.StandardStringFormatBotVerifyInfoDecoder.decode(BotVerifyInfo.kt:342) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.bot.StandardStringFormatBotVerifyInfoDecoder.decode(BotVerifyInfo.kt:328) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.bot.StandardSerialFormatBotVerifyInfoDecoder.decode(BotVerifyInfo.kt:321) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.bot.DecoderBotVerifyInfo.decode(BotVerifyInfos.kt:53) ~[simbot-api-3.2.0.jar:?]
	at love.forte.simbot.component.kook.bot.KookBotManager.register(KookBotManager.kt:112) ~[simbot-component-kook-core-3.2.0.0-alpha.8-dev.3.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor.register(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:244) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor.config(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:148) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootBotAutoRegisterBuildConfigure$SimbotSpringBootBotAutoRegisterPostProcessor.processApplication(SimbotSpringBootBotAutoRegisterBuildConfigure.kt:55) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootApplicationConfiguration$simbotApplicationAfterApplication$1.invokeSuspend(SimbotSpringBootApplicationConfiguration.kt:130) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at love.forte.simbot.utils.DefaultRunInNoScopeBlockingStrategy.invoke(BlockingRunner.kt:423) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simbot.utils.BlockingRunnerKt.runInNoScopeBlocking(BlockingRunner.kt:496) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simbot.utils.BlockingRunnerKt.runInNoScopeBlocking$default(BlockingRunner.kt:493) ~[simbot-util-suspend-transformer-jvm-3.2.0.jar:?]
	at love.forte.simboot.spring.autoconfigure.SimbotSpringBootApplicationConfiguration.simbotApplicationAfterApplication(SimbotSpringBootApplicationConfiguration.kt:129) ~[simboot-core-spring-boot-starter-3.2.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.11.jar:6.0.11]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.11.jar:6.0.11]
	... 24 more
```

**Comment by ForteScarlet** [comment]
配置文件内容稍有变动，可临时参考 https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook.bot/-kook-bot-verify-info-configuration/index.html 中的 `config.syncPeriods` 配置示例

`syncPeriods` 的配置项默认值处理有些问题，后续此问题应当会被优化

**Comment by axiangcoding** [comment]
> 配置文件内容稍有变动，可临时参考 https://docs.simbot.forte.love/components/kook/simbot-component-kook-core/love.forte.simbot.component.kook.bot/-kook-bot-verify-info-configuration/index.html 中的 `config.syncPeriods` 配置示例
> 
> `syncPeriods` 的配置项默认值处理有些问题，后续此问题应当会被优化

基于此链接中的样例使用配置项不再报错
