### ISSUE TITLE
私信撤回产生的JSON反序列错误

### ISSUE THREAD

**Issue by mirai-MIC** [ForteScarlet/simpler-robot#741]
### 版本号

.2.0.0-alpha.8-dev.3

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

KOOK

### 问题描述

一旦和bot私信撤回之后，会出现一个json序列化错误，并且会在控制台持续不间断的打印这个错误，

### 复现方式

在和bot的私聊中撤回任意消息

### 相关日志

```Text
2023-09-03T12:29:35.758+08:00 ERROR 11496 --- [       task-153] l.f.simbot.kook.bot.J6eTq84pFXjmdKqc     : Session received frame failed: Polymorphic serializer was not found for class discriminator 'private_message_deleted'
JSON input: .....7572","create_at":1693715030054,"deleted_at":1693715040312}}, try to re-receive.

kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for class discriminator 'private_message_deleted'
JSON input: .....7572","create_at":1693715030054,"deleted_at":1693715040312}}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.json.internal.PolymorphicKt.throwSerializerNotFound(Polymorphic.kt:79) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:68) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:280) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:297) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:280) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at love.forte.simbot.kook.event.Event$$serializer.deserialize(Event.kt:36) ~[simbot-component-kook-api-jvm-3.2.0.0-alpha.8-dev.3.jar:na]
	at love.forte.simbot.kook.event.Event$$serializer.deserialize(Event.kt:36) ~[simbot-component-kook-api-jvm-3.2.0.0-alpha.8-dev.3.jar:na]
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:280) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:297) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:280) ~[kotlinx-serialization-core-jvm-1.5.1.jar:1.5.1]
	at love.forte.simbot.kook.event.Signal$Event$$serializer.deserialize(Signal.kt:138) ~[simbot-component-kook-api-jvm-3.2.0.0-alpha.8-dev.3.jar:na]
	at love.forte.simbot.kook.event.Signal$Event$$serializer.deserialize(Signal.kt:138) ~[simbot-component-kook-api-jvm-3.2.0.0-alpha.8-dev.3.jar:na]
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:25) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:127) ~[kotlinx-serialization-json-jvm-1.5.1.jar:na]
	at love.forte.simbot.kook.internal.Receiving.processSignalString(BotStates.kt:530) ~[simbot-component-kook-stdlib-jvm-3.2.0.0-alpha.8-dev.3.jar:na]
	at love.forte.simbot.kook.internal.Receiving.invoke(BotStates.kt:462) ~[simbot-component-kook-stdlib-jvm-3.2.0.0-alpha.8-dev.3.jar:na]
	at love.forte.simbot.kook.internal.Receiving$invoke$1.invokeSuspend(BotStates.kt) ~[simbot-component-kook-stdlib-jvm-3.2.0.0-alpha.8-dev.3.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.22.jar:1.8.22-release-407(1.8.22)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

**Comment by ForteScarlet** [comment]
异常原因是 api 模块尚未支持私聊消息撤回事件。
但是此异常日志应当不会影响事件的正常处理流程才对，也未复现出 **“会在控制台持续不间断的打印这个错误”** 的情况。
