### ISSUE TITLE
启动报错 NoClassDefFoundError: kotlin/enums/EnumEntriesKt

### ISSUE THREAD

**Issue by 1072633675** [ForteScarlet/simpler-robot#876]
### 版本号

4.2

### 涉及的编程语言

Java

### 涉及的组件库

OneBot

### 疑问描述

![屏幕截图 2024-07-12 162740](https://github.com/user-attachments/assets/ca841041-f619-414b-9efb-d5806a461ff4)
![屏幕截图 2024-07-12 162858](https://github.com/user-attachments/assets/f01ac8f4-be69-43c0-b81a-70f998270767)
Error creating bean with name 'formContentFilter' defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration.class]: Failed to instantiate [org.springframework.boot.web.servlet.filter.OrderedFormContentFilter]: Factory method 'formContentFilter' threw exception with message: Could not initialize class kotlinx.serialization.json.Json

**Comment by 1072633675** [comment]
![屏幕截图 2024-07-12 163122](https://github.com/user-attachments/assets/dd8377f8-b02c-4fd8-b4ba-b70f5f2c62b3)
yml是文档一个没动的

**Comment by ForteScarlet** [comment]
`Could not initialize class kotlinx.serialization.json.Json`

SpringWeb由于找不到 Kotlinx JSON 而无法启动。检查项目依赖或配置，simbot应当并不会修改spring的序列化配置才是。
或者尝试移除simbot相关依赖后再启动并观察情况。

**Comment by 1072633675** [comment]
![image](https://github.com/user-attachments/assets/ac52b4b3-29e2-42ec-b990-0b03f3324ef1)
全部了 还有就是spring boot3.0和web

**Comment by ForteScarlet** [comment]
移除它们、只保留spring的情况下能够正常启动吗

**Comment by 1072633675** [comment]
能

**Comment by ForteScarlet** [comment]
尝试添加 `simbot-core-spring-boot-starter`、`simbot-component-onebot-v11-core-jvm`、`ktor-client-java-jvm` 这三个，能正常启动吗

**Comment by 1072633675** [comment]
![屏幕截图 2024-07-12 164347](https://github.com/user-attachments/assets/f82b5d59-7784-4b46-b6f8-5d3efa9160a8)
这sange三个依赖任一放出一个 都是一样的报错。@EnableSimbot注销的

**Comment by 1072633675** [comment]
![屏幕截图 2024-07-12 164505](https://github.com/user-attachments/assets/98ae0221-fe0c-4121-887f-e8ea89b9b14f)
启动zhengc正常

**Comment by 1072633675** [comment]
![屏幕截图 2024-07-12 164558](https://github.com/user-attachments/assets/af74573b-2a08-404f-9143-a004ff494533)
其他配置

**Comment by ForteScarlet** [comment]
可否提供一个能用于复现此问题的最小项目，比如现在用的这个（如有敏感信息请注意清理）

**Comment by 1072633675** [comment]
没了 截图已经是全部项目的样子了

**Comment by ForteScarlet** [comment]
那这个项目可以打个压缩包提供一下吗，我尝试在本地复现

**Comment by 1072633675** [comment]
https://github.com/1072633675/Test.git 是这样吗 我给src和pom.xml打包上传上仓库了

**Comment by ForteScarlet** [comment]
以及，既然是类缺失问题，临时解决办法：尝试手动添加 Kotlinx JSON 依赖：
```xml
<dependency>
<groupId>org.jetbrains.kotlinx</groupId>
<artifactId>kotlinx-serialization-json</artifactId>
<version>1.7.1</version>
</dependency>
```

相关仓库：https://github.com/Kotlin/kotlinx.serialization

**Comment by ForteScarlet** [comment]
其实issue的这个评论是可以直接粘贴文件的

**Comment by 1072633675** [comment]
zip拖过来空掉了

**Comment by ForteScarlet** [comment]
没事，我从你这个git里下载了

**Comment by ForteScarlet** [comment]
实际出现的异常是：
```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt [in thread "background-preinit"]
	at kotlinx.serialization.json.ClassDiscriminatorMode.<clinit>(JsonConfiguration.kt:133) ~[kotlinx-serialization-json-jvm-1.6.3.jar:na]
	at kotlinx.serialization.json.JsonConfiguration.<init>(JsonConfiguration.kt:41) ~[kotlinx-serialization-json-jvm-1.6.3.jar:na]
	at kotlinx.serialization.json.Json$Default.<init>(Json.kt:71) ~[kotlinx-serialization-json-jvm-1.6.3.jar:na]
	at kotlinx.serialization.json.Json$Default.<init>(Json.kt) ~[kotlinx-serialization-json-jvm-1.6.3.jar:na]
	at kotlinx.serialization.json.Json.<clinit>(Json.kt) ~[kotlinx-serialization-json-jvm-1.6.3.jar:na]
	at org.springframework.http.converter.json.KotlinSerializationJsonHttpMessageConverter.<init>(KotlinSerializationJsonHttpMessageConverter.java:47) ~[spring-web-6.0.2.jar:6.0.2]
	at org.springframework.http.converter.support.AllEncompassingFormHttpMessageConverter.<init>(AllEncompassingFormHttpMessageConverter.java:82) ~[spring-web-6.0.2.jar:6.0.2]
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$MessageConverterInitializer.run(BackgroundPreinitializer.java:140) ~[spring-boot-autoconfigure-3.0.0.jar:3.0.0]
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.runSafely(BackgroundPreinitializer.java:114) ~[spring-boot-autoconfigure-3.0.0.jar:3.0.0]
	at org.springframework.boot.autoconfigure.BackgroundPreinitializer$1.run(BackgroundPreinitializer.java:103) ~[spring-boot-autoconfigure-3.0.0.jar:3.0.0]
	at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
```

在 `properties` 中添加属性 `kotlin.version` 并指定大于等于simbot使用的Kotlin版本（目前是 `2.0.0`）：

```xml
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <!-- 指定版本 -->
        <kotlin.version>2.0.0</kotlin.version>
    </properties>
```

然后清理并重新编译项目，然后再做尝试。

相关参考：
- https://github.com/orgs/simple-robot/discussions/190
- https://github.com/orgs/simple-robot/discussions/183
- [Spring官方文档: Kotlin Support - Dependency management](https://docs.spring.io/spring-boot/reference/features/kotlin.html#features.kotlin.dependency-management)
