### ISSUE TITLE
启动项目报错，Caused by: java.lang.ClassNotFoundException: kotlin.enums.EnumEntriesKt

### ISSUE THREAD

**Issue by ityaquan** [ForteScarlet/simpler-robot#926]
### 是否会提供贡献？

否

### 版本号

4.6.0

### 涉及的编程语言

Java

### 项目构建工具

Maven

### 涉及的组件库

QQ机器人

### 问题描述

启动项目时报错
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>love.forte.simbot</groupId>
            <artifactId>simbot-core-spring-boot-starter</artifactId>
            <version>4.6.0</version>
        </dependency>
        <dependency>
            <groupId>love.forte.simbot.component</groupId>
            <artifactId>simbot-component-qq-guild-core-jvm</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>io.ktor</groupId>
            <artifactId>ktor-client-java-jvm</artifactId>
            <version>2.3.11</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

### 复现方式

启动项目时报错

### 相关日志

```Text
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springApplicationConfigurationProperties' defined in love.forte.simbot.spring.configuration.SimbotSpringPropertiesConfiguration: Failed to instantiate [love.forte.simbot.spring.common.application.SpringApplicationConfigurationProperties]: Factory method 'springApplicationConfigurationProperties' threw exception with message: kotlin/enums/EnumEntriesKt
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:657) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:491) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1324) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1161) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.2.jar:3.0.2]
	at com.duck.duckbot.DuckBotApplication.main(DuckBotApplication.java:15) ~[classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [love.forte.simbot.spring.common.application.SpringApplicationConfigurationProperties]: Factory method 'springApplicationConfigurationProperties' threw exception with message: kotlin/enums/EnumEntriesKt
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.4.jar:6.0.4]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-6.0.4.jar:6.0.4]
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt
	at love.forte.simbot.spring.common.application.BotConfigResourceLoadFailurePolicy.<clinit>(SpringApplicationConfigurationProperties.kt:240) ~[simbot-core-spring-boot-starter-common-4.6.0.jar:na]
	at love.forte.simbot.spring.common.application.SpringApplicationConfigurationProperties$BotProperties.<init>(SpringApplicationConfigurationProperties.kt:70) ~[simbot-core-spring-boot-starter-common-4.6.0.jar:na]
	at love.forte.simbot.spring.common.application.SpringApplicationConfigurationProperties.<init>(SpringApplicationConfigurationProperties.kt:41) ~[simbot-core-spring-boot-starter-common-4.6.0.jar:na]
	at love.forte.simbot.spring.configuration.SimbotSpringPropertiesConfiguration.springApplicationConfigurationProperties(SimbotSpringPropertiesConfiguration.kt:46) ~[simbot-core-spring-boot-starter-4.6.0.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.4.jar:6.0.4]
	... 19 common frames omitted
Caused by: java.lang.ClassNotFoundException: kotlin.enums.EnumEntriesKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
	... 28 common frames omitted
```

### 其他补充

无

**Comment by ForteScarlet** [comment]
可参考 https://github.com/orgs/simple-robot/discussions/183 ，不过目前Kotlin版本 `kotlin.version` 推荐配置为 `2.0.0` 或以上

**Comment by ForliyScarlet** [comment]
此issue已经在「等待反馈」状态下5日未应答。如果在「陈旧」状态下逾期2日将会被视为无效过期并关闭。

**Comment by ForliyScarlet** [comment]
此issue已经在「陈旧」状态下逾期2日未应答, 视为无效过期并关闭。
